### ISSUE TITLE
Index.html has an extra '\r' at end of line?

### ISSUE THREAD

**Issue by ghomem** [eddelbuettel/html5-story#1]
Vim was displaying ^M symbols at the end.

```
cat index.html |tr -d '\r' > index2.html
mv index2.html index.html
```

fixes it.

**Comment by eddelbuettel** [comment]
That may be true but recall that I didn't write / create html5-story -- it really comes from https://html5up.net as stated.

I have not worked on a DOS or Windows files systems in decades so it is mildly amusing to me too but as it a) does not get in the way and b) it seems like good practice to make minimal changes to borrowed frameworks I left it as is, and think that is the right call.   So I'll close this.

(I'm not a Vim expert as I live in Emacs but I am fairly sure you can also tell Vim to simply not display those end-of-line chars.  Most editors are happy to deal with files from real files as well as "those files".)

**Comment by ghomem** [comment]
Sorry @eddelbuettel, I thought you were the creator of this wonderful template. You are right, this is nothing serious, of course.
